#!/usr/bin/python

from random import randrange

def get_rand_alpha_num():
	r = randrange(0,60)
	if   r >= 0  and r < 10: return chr(r+48)
	elif r >= 10 and r < 35: return chr((r-10)+65)
	elif r >= 35 and r < 60: return chr((r-35)+97)

password = [get_rand_alpha_num() for i in range(0,12)]
print "".join(password)
